docs_dir: src
site_name: Abls-Habitat Docs
site_url: https://docs.abls-habitat.fr/
repo_url: https://github.com/sebaru/abls-habitat-docs
edit_uri: blob/main/src
repo_name: Abls-Habitat Repository
site_description: Home Automation by Abls-Habitat
site_author: Sébastien et Bruno Lefèvre
site_dir: build
extra_css: [extra.css]

nav:

 - Découverte:
   - Tour d'horizon: index.md
   - Galerie: galerie.md
 - Prise en main:
   - Guide de démarrage: guide_demarrage.md
   - Architecture: architecture.md
 - Guide de l'utilisateur:
   - Les Utilisateurs: users.md
 - Connecteurs:
   - Description: connecteurs.md
   - I/O Wago modbus: io_modbus.md
   - I/O RaspberryPI: io_gpiod.md
   - I/O Phidget: io_phidget.md
   - Audio output: io_audio.md
   - Instant Messaging: io_imsgs.md
   - SMS Short Message System: io_smsg.md
   - E.D.F Teleinfo: io_teleinfoedf.md
   - UPS Uninterruptible Power Supply: io_ups.md
   - DMX Projecteurs: io_dmx.md
   - Benq Projecteurs: io_projo.md
 - D.L.S:
   - Le concept: dls.md
   - Les acronymes: dls_acronymes.md
   - Les liens: dls_link.md
   - La logique: dls_logique.md
   - Les calculs: dls_calculs.md
   - Les entrées T.O.R: dls_entre_tor.md
   - Les Visuels: dls_visuels.md
 - Mapping:
   - Lien entre connecteur et D.L.S: mapping.md
 - Visuels:
   - L'inventaire de visuels: visuels.md
   - Les boutons: dls_visuel_bouton.md
   - Les commentaires: dls_visuel_comment.md
 - Contacts:
   - Qui sommes-nous ?: auteurs.md

theme:
 name: material
 logo: https://static.abls-habitat.fr/img/abls.svg
 locale: fr
 features:
  - navigation.tabs
 palette:
  - scheme: default

extra:
  social:
    - icon: fontawesome/brands/github # (1)!
      link: https://github.com/sebaru

plugins:
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
  - search

markdown_extensions:
  - admonition
