docs_dir: src
site_name: Abls-Habitat Docs
site_url: https://docs.abls-habitat.fr/
repo_url: https://github.com/sebaru
repo_name: Abls-Habitat Repository
site_description: Home Automation by Abls-Habitat
site_author: Sébastien et Bruno Lefèvre
site_dir: build
extra_css: [extra.css]

nav:

 - Découverte:
   - Tour d'horizon: index.md
   - Galerie: galerie.md
 - Prise en main:
   - Guide de démarrage: guide_demarrage.md
 - Guide de l'utilisateur:
   - Typologie des Utilisateurs: users.md
 - Les connecteurs:
   - I/O Wago modbus: io_modbus.md
   - I/O RaspberryPI: io_gpiod.md
   - I/O Phidget: io_phidget.md
   - Audio output: io_audio.md
   - Instant Messaging: io_imsgs.md
   - SMS Short Message System: io_smsg.md
   - E.D.F Teleinfo: io_teleinfoedf.md
   - UPS Uninterruptible Power Supply: io_ups.md
   - DMX Projecteurs: io_dmx.md
   - Benq Projecteurs: io_projo.md
 - Programmation D.L.S:
   - Le concept: dls.md
   - Les acronymes: dls_acronymes.md
   - Les liens: dls_link.md
   - La logique: dls_logique.md
   - Les calculs: dls_calculs.md
   - Les entrées T.O.R: dls_entre_tor.md
   - Les Visuels: dls_visuels.md
 - Les formes de visuels:
   - Les boutons: dls_visuel_bouton.md
   - Les commentaires: dls_visuel_comment.md
   - Inventaire des Visuels: visuels.md
 - Pour nous aider:
   - Qui sommes-nous ?: auteurs.md

theme:
 name: readthedocs
 locale: fr

markdown_extensions:
  - admonition
